#!/usr/bin/env python3
"""Small, dependency-free Jellyfin adapter for Jukebox.

The access token is read from a 0600 config file (or the environment).  Stream
URLs deliberately contain no credentials; mpv receives the token through a
private, short-lived config file generated by ``mpv-config``.
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import uuid
from pathlib import Path
from typing import Any


APP_NAME = "Jukebox"
APP_VERSION = "1.0"
UNIT_SEPARATOR = "\x1f"


class JellyfinError(RuntimeError):
    pass


def config_path() -> Path:
    configured = os.environ.get("JUKEBOX_JELLYFIN_CONFIG")
    if configured:
        return Path(configured).expanduser()
    root = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return root / "jukebox" / "jellyfin.json"


def load_config(require_token: bool = True) -> dict[str, Any]:
    data: dict[str, Any] = {}
    path = config_path()
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise JellyfinError(f"cannot read {path}: {exc}") from exc

    env_map = {
        "server": "JUKEBOX_JELLYFIN_URL",
        "token": "JUKEBOX_JELLYFIN_TOKEN",
        "user_id": "JUKEBOX_JELLYFIN_USER_ID",
    }
    for key, env_name in env_map.items():
        if os.environ.get(env_name):
            data[key] = os.environ[env_name]

    if data.get("server"):
        data["server"] = str(data["server"]).rstrip("/")
    data.setdefault("device_id", str(uuid.uuid4()))
    if not data.get("server"):
        raise JellyfinError("Jellyfin is not configured; run: jukebox jellyfin-login SERVER")
    if require_token and not data.get("token"):
        raise JellyfinError("Jellyfin token is missing; run: jukebox jellyfin-login SERVER")
    return data


def save_config(data: dict[str, Any]) -> None:
    path = config_path()
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    payload = json.dumps(data, indent=2, sort_keys=True) + "\n"
    fd, tmp_name = tempfile.mkstemp(prefix=".jellyfin-", dir=path.parent, text=True)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(payload)
        os.replace(tmp_name, path)
        os.chmod(path, 0o600)
    finally:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass


def auth_header(config: dict[str, Any], include_token: bool = True) -> str:
    values = {
        "Client": APP_NAME,
        "Device": os.uname().nodename,
        "DeviceId": config["device_id"],
        "Version": APP_VERSION,
    }
    if include_token and config.get("token"):
        values["Token"] = config["token"]
    return "MediaBrowser " + ", ".join(f'{key}="{value}"' for key, value in values.items())


def request(
    config: dict[str, Any],
    path: str,
    *,
    method: str = "GET",
    body: dict[str, Any] | None = None,
    raw: bool = False,
    include_token: bool = True,
) -> Any:
    url = config["server"] + "/" + path.lstrip("/")
    data = json.dumps(body).encode() if body is not None else None
    headers = {
        "Accept": "*/*" if raw else "application/json",
        "Authorization": auth_header(config, include_token=include_token),
        "User-Agent": f"{APP_NAME}/{APP_VERSION}",
    }
    if data is not None:
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            payload = response.read()
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace").strip()
        raise JellyfinError(f"Jellyfin returned HTTP {exc.code}: {detail or exc.reason}") from exc
    except urllib.error.URLError as exc:
        raise JellyfinError(f"cannot reach Jellyfin at {config['server']}: {exc.reason}") from exc
    if raw:
        return payload
    if not payload:
        return None
    return json.loads(payload)


def clean_field(value: Any) -> str:
    if value is None:
        return ""
    return str(value).replace("\t", " ").replace("\r", " ").replace("\n", " ")


def item_stream_url(config: dict[str, Any], item: dict[str, Any]) -> str:
    item_id = urllib.parse.quote(str(item["Id"]), safe="")
    # Jellyfin 10.11 can return HTTP 500 from /Audio/{id}/stream for otherwise
    # healthy audio items. The Download endpoint supports HTTP ranges and sends
    # the untouched original file, making it a reliable direct-play source.
    return f"{config['server']}/Items/{item_id}/Download"


def item_to_cache_row(config: dict[str, Any], item: dict[str, Any]) -> list[str]:
    artists = item.get("Artists") or []
    artist = ", ".join(str(a) for a in artists if a) or item.get("AlbumArtist") or "Unknown"
    ticks = item.get("RunTimeTicks") or 0
    try:
        duration = str(float(ticks) / 10_000_000)
    except (TypeError, ValueError):
        duration = "0"
    date = item.get("ProductionYear") or str(item.get("PremiereDate") or "")[:4] or "0"
    return [
        item_stream_url(config, item),
        item.get("Name") or "Unknown",
        artist,
        item.get("Album") or "Unknown",
        date,
        duration,
        item.get("IndexNumber") or 0,
        item.get("ParentIndexNumber") or 1,
    ]


def atomic_write(path: Path, content: str, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}-", dir=path.parent, text=True)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp_name, path)
        os.chmod(path, mode)
    finally:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass


def command_login(args: argparse.Namespace) -> int:
    existing: dict[str, Any] = {}
    try:
        existing = load_config(require_token=False)
    except JellyfinError:
        pass
    server = (args.server or existing.get("server") or input("Jellyfin server URL: ")).rstrip("/")
    username = args.username or input("Jellyfin username: ")
    password = getpass.getpass("Jellyfin password: ")
    config = {
        "server": server,
        "device_id": existing.get("device_id", str(uuid.uuid4())),
    }
    result = request(
        config,
        "/Users/AuthenticateByName",
        method="POST",
        body={"Username": username, "Pw": password},
        include_token=False,
    )
    config.update(
        token=result.get("AccessToken"),
        user_id=(result.get("User") or {}).get("Id"),
        username=(result.get("User") or {}).get("Name", username),
    )
    if not config["token"] or not config["user_id"]:
        raise JellyfinError("login succeeded but Jellyfin returned no user token")
    save_config(config)
    print(f"Connected to {server} as {config['username']}; credentials saved in {config_path()}")
    return 0


def command_status(_args: argparse.Namespace) -> int:
    config = load_config()
    user = request(config, f"/Users/{urllib.parse.quote(str(config.get('user_id', '')), safe='')}")
    print(f"Connected: {config['server']} as {user.get('Name', config.get('username', 'unknown'))}")
    return 0


def command_logout(_args: argparse.Namespace) -> int:
    path = config_path()
    try:
        config = load_config()
        request(config, "/Sessions/Logout", method="POST")
    except JellyfinError:
        pass
    try:
        path.unlink()
    except FileNotFoundError:
        pass
    print(f"Removed {path}")
    return 0


def command_sync(args: argparse.Namespace) -> int:
    config = load_config()
    user_id = config.get("user_id")
    if not user_id:
        raise JellyfinError("user id is missing; log in again")
    params = urllib.parse.urlencode(
        {
            "Recursive": "true",
            "IncludeItemTypes": "Audio",
            "Fields": "MediaSources,Genres,DateCreated,PremiereDate,ProductionYear",
            "SortBy": "SortName",
            "SortOrder": "Ascending",
        }
    )
    result = request(config, f"/Users/{urllib.parse.quote(str(user_id), safe='')}/Items?{params}")
    items = result.get("Items", []) if isinstance(result, dict) else []
    rows = [item_to_cache_row(config, item) for item in items if item.get("Id")]
    content = "".join("\t".join(clean_field(field) for field in row) + "\n" for row in rows)
    atomic_write(Path(args.cache), content)
    print(f"Jellyfin: {len(rows)} tracks", file=sys.stderr)
    return 0


STREAM_RE = re.compile(r"/Audio/([^/?]+)/stream(?:\.[^?/]*)?(?:\?|$)")
DOWNLOAD_RE = re.compile(r"/Items/([^/?]+)/Download(?:\?|$)")


def item_id_from_reference(reference: str) -> str:
    match = DOWNLOAD_RE.search(reference) or STREAM_RE.search(reference)
    if not match:
        raise JellyfinError("not a Jukebox Jellyfin stream URL")
    return urllib.parse.unquote(match.group(1))


def command_art(args: argparse.Namespace) -> int:
    config = load_config()
    item_id = urllib.parse.quote(item_id_from_reference(args.reference), safe="")
    try:
        payload = request(config, f"/Items/{item_id}/Images/Primary?maxWidth={args.max_width}", raw=True)
    except JellyfinError:
        return 1
    path = Path(args.output)
    path.write_bytes(payload)
    os.chmod(path, 0o600)
    return 0 if payload else 1


def normalize_lyrics(payload: Any) -> list[tuple[int, str]]:
    if not isinstance(payload, dict):
        return []
    entries = payload.get("Lyrics") or payload.get("lyrics") or []
    output: list[tuple[int, str]] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        text = clean_field(entry.get("Text") or entry.get("text"))
        if not text:
            continue
        start = entry.get("Start", entry.get("start"))
        try:
            # Jellyfin lyric timestamps are ticks (100 ns).
            start_ms = int(start) // 10_000 if start is not None else -1
        except (TypeError, ValueError):
            start_ms = -1
        output.append((start_ms, text))
    return output


LRC_RE = re.compile(r"\[(\d{1,3}):(\d{2})(?:[.:](\d{1,3}))?\](.*)")


def parse_lrc(text: str) -> list[tuple[int, str]]:
    output: list[tuple[int, str]] = []
    plain: list[str] = []
    for raw_line in text.splitlines():
        matches = list(LRC_RE.finditer(raw_line))
        if matches:
            for match in matches:
                fraction = match.group(3) or "0"
                millis = int((fraction + "00")[:3])
                start_ms = (int(match.group(1)) * 60 + int(match.group(2))) * 1000 + millis
                lyric = match.group(4).strip()
                if lyric:
                    output.append((start_ms, clean_field(lyric)))
        elif raw_line.strip() and not re.match(r"^\[[a-zA-Z]+:", raw_line):
            plain.append(clean_field(raw_line.strip()))
    if output:
        return sorted(output)
    return [(-1, line) for line in plain]


def local_lyrics(reference: str) -> list[tuple[int, str]]:
    path = Path(reference)
    for suffix in (".lrc", ".elrc", ".txt"):
        candidate = path.with_suffix(suffix)
        if candidate.is_file():
            return parse_lrc(candidate.read_text(encoding="utf-8", errors="replace"))
    try:
        probe = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", "--", reference],
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )
        tags = json.loads(probe.stdout).get("format", {}).get("tags", {})
        lower = {str(key).lower(): value for key, value in tags.items()}
        embedded = lower.get("lyrics") or lower.get("unsyncedlyrics")
        return parse_lrc(str(embedded)) if embedded else []
    except (OSError, subprocess.SubprocessError, json.JSONDecodeError):
        return []


def command_lyrics(args: argparse.Namespace) -> int:
    if args.reference.startswith(("http://", "https://")):
        config = load_config()
        item_id = urllib.parse.quote(item_id_from_reference(args.reference), safe="")
        try:
            lines = normalize_lyrics(request(config, f"/Audio/{item_id}/Lyrics"))
        except JellyfinError:
            lines = []
    else:
        lines = local_lyrics(args.reference)
    for start_ms, lyric in lines:
        print(f"{start_ms}{UNIT_SEPARATOR}{lyric}")
    return 0 if lines else 1


def command_mpv_config(args: argparse.Namespace) -> int:
    config = load_config()
    token = str(config["token"]).replace("\n", "").replace("\r", "")
    # This file is mode 0600 and contains the only playback-side copy of the token.
    content = f"http-header-fields=X-Emby-Token: {token}\nuser-agent={APP_NAME}/{APP_VERSION}\n"
    atomic_write(Path(args.output), content)
    return 0


def command_cache_row(args: argparse.Namespace) -> int:
    try:
        with open(args.cache, encoding="utf-8") as cache:
            for line in cache:
                fields = line.rstrip("\n").split("\t")
                if fields and fields[0] == args.reference:
                    print(UNIT_SEPARATOR.join(fields[1:]))
                    return 0
    except OSError as exc:
        raise JellyfinError(f"cannot read metadata cache: {exc}") from exc
    return 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    login = sub.add_parser("login")
    login.add_argument("server", nargs="?")
    login.add_argument("--username")
    login.set_defaults(func=command_login)
    sub.add_parser("status").set_defaults(func=command_status)
    sub.add_parser("logout").set_defaults(func=command_logout)
    sync = sub.add_parser("sync")
    sync.add_argument("--cache", required=True)
    sync.set_defaults(func=command_sync)
    art = sub.add_parser("art")
    art.add_argument("reference")
    art.add_argument("output")
    art.add_argument("--max-width", type=int, default=1000)
    art.set_defaults(func=command_art)
    lyrics = sub.add_parser("lyrics")
    lyrics.add_argument("reference")
    lyrics.set_defaults(func=command_lyrics)
    mpv_config = sub.add_parser("mpv-config")
    mpv_config.add_argument("output")
    mpv_config.set_defaults(func=command_mpv_config)
    cache_row = sub.add_parser("cache-row")
    cache_row.add_argument("--cache", required=True)
    cache_row.add_argument("reference")
    cache_row.set_defaults(func=command_cache_row)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        return int(args.func(args) or 0)
    except (JellyfinError, json.JSONDecodeError) as exc:
        print(f"jukebox: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
